# Generated by Django 4.2.1 on 2023-06-05 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_list_score_list_body_list_thumbnail_list_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="Author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
