# Generated by Django 4.2.1 on 2023-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_list_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="slug",
            field=models.SlugField(default=None),
        ),
    ]
